version: '3'
services:
  ryu:
    image: ryu-controller
    build:
      context: ryu/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '6633:6633'
      - '6653:6653'
    expose:
      - '8080'
      - '6633'
      - '6653'
  asterisk:
    image: asterisk-ari
    build:
      context: asterisk/
      dockerfile: Dockerfile
    expose:
      - '8088'
    ports:
      - '8088:8088'
    depends_on:
      - ryu
  call_admission_control_frontend:
    image: cac-frontend
    build:
      context: call-admission-control/src/frontend/
      dockerfile: Dockerfile
    expose:
      - '3000'
    ports:
      - '3000:3000'
  call_admission_control_backend:
    image: cac-backend
    build:
      context: call-admission-control/src/backend/
      dockerfile: Dockerfile
    expose:
      - '8000'
    ports:
      - '8000:8000'
    depends_on:
      - call_admission_control_frontend
      - asterisk
      - ryu
  mininet:
    image: cac-mininet
    ports:
      - '6632:6632'
    expose:
      - '6632'
    build:
      context: mininet/
      dockerfile: Dockerfile
    tty: true
    privileged: true
    depends_on:
      - ryu

