version: '3'
services:
  ryu:
    image: ryu-controller
    build:
      context: ryu/
      dockerfile: Dockerfile
    ports:
      - '8080:8080/tcp'
  asterisk:
    image: asterisk-ari
    build:
      context: asterisk/
      dockerfile: Dockerfile
    ports:
      - '8088:8088/tcp'
    depends_on:
      - ryu
  call_admission_control_frontend:
    image: cac-frontend
    build:
      context: call-admission-control/src/frontend/
      dockerfile: Dockerfile
    ports:
      - '3000:3000/tcp'
  call_admission_control_backend:
    image: cac-backend
    build:
      context: call-admission-control/src/backend/
      dockerfile: Dockerfile
    ports:
      - '8000:8000/tcp'
    depends_on:
      - call_admission_control_frontend
      - asterisk
      - ryu